# Generated by Django 6.0.5 on 2026-06-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('grado', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('docente', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
